### ISSUE TITLE
Vue Routes Loaded with Dynamic Import Aren't Working

### ISSUE THREAD

**Issue by milky2028** [surma/rollup-plugin-off-main-thread#15]
I'm trying to build a minimal Vue app that's somewhat equivalent to the default webpack config.

I'm formatting as AMD, as the plugin requires, but I can't seem to get lazy-loaded modules to work. I know this plugin brings in its own AMD loader that resolves AMD modules. It works fine when commenting out the worker code and compiling to ESM, but then, of course, all the benefits of this plugin are lost. The default AMD loader via require.js doesn't seem to be much help either.

Any help would be much appreciated!

[My repo](https://github.com/milky2028/vue-rollup)

```javascript
import Vue from 'vue';
import VueRouter from 'vue-router';

// works fine with when compiling to AMD and ESM
import Home from '../views/Home.vue';
// does not work with AMD, works with ESM
const About = () => import('../views/About.vue');
```

**Comment by surma** [comment]
Sorry for not getting back to this sooner.

I don’t have a deep understanding of Vue, but I think what you are doing is not what Vue can handle.
The default export of `../views/About.vue` is a function that returns a view/component. In your case, `About` is now a function that returns a _promise_ for a _module_. I tried fixing it, but I don’t quite know how. The module loading itself works just fine, so the problem isn’t with the plugin. Sorry.

**Comment by milky2028** [comment]
I apologize for not getting back to the getting back to sooner!

I think this is definitely some sort of issue with using Vue with AMD. I'm intermittently trying to figure it out. Thanks for your help nonetheless!e
