### ISSUE TITLE
Remove {type: "module"}

### ISSUE THREAD

**Issue by surma** [surma/rollup-plugin-off-main-thread#18]
via @lukastaegert 

> Automatically remove {type: "module"} from new Worker calls. This will allow for isomorphic setups where you are not bundling in development but just use a bowser that supports module workers. But admittedly, keeping it may not actually cause issues...

**Comment by surma** [comment]
I now remove the `type` field from the options object. This is published in v1.4.0 :)

**Comment by lukastaegert** [comment]
Wow, that was quick. Thanks a lot, great work! ❤️
