### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by Dmitry-N-Medvedev** [surma/rollup-plugin-off-main-thread#20]
hi,

the following line:
```js
ws_comm = new Worker('../communication/ws.worker.js', { type: 'module' });
```

...gets converted to this:
```js
ws_comm = new Worker(import.meta.ROLLUP_FILE_URL_ecbdacb6, {});
```

with the following error:
```js
ws_comm = new Worker(import.meta.ROLLUP_FILE_URL_ecbdacb6, {}); // { type: 'module' }
                           ^
```

**Comment by surma** [comment]
Can you put a reproduction in a gist or something?  I have a bunch of tests that should cover this and they are passing.

**Comment by Dmitry-N-Medvedev** [comment]
@surma , sorry for being late.

here is the link: https://github.com/Dmitry-N-Medvedev/web-experiments/tree/posts

please see the [readme](https://github.com/Dmitry-N-Medvedev/web-experiments/blob/posts/README.md) on how to start it.

**Comment by Dmitry-N-Medvedev** [comment]
okey, here is what I have found: the plugin generates incorrect include path:

the `import wsWorkerURL from 'omt:./workers/ws.worker.js';` would generate

```js
./ws.worker.20f57ed2.js
```

instead of

```js
client/ws.worker.20f57ed2.js
```

**Comment by surma** [comment]
I’m pretty sure this is fixed. Please re-open if that’s not the case.
