### ISSUE TITLE
isEsmOutput option not parsing correctly

### ISSUE THREAD

**Issue by stefan-pdx** [surma/rollup-plugin-off-main-thread#22]
Hello,

Thank you for this awesome package! This has been my go-to fork being able to integrate modules with Web Workers.

I've come across an issue where the `isEsmOutput` option isn't being correctly parsed when `rollup.config.js` is configured to output to `esm`. The `{type: "module"}` argument that's passed into the worker is being removed. I've narrowed it down to this specific line in index.js:

```javascript
if (!isEsmOutput) {
    // The below line needs to be commented out.
    delete optionsObject.type;
}
```

Commenting it out fixes it. I started in investigate and found that `outputOptions` was running _after_ transform, so `isEsmOutput` wasn't being calculated correctly. After that I started reading up on Rollup hooks but ended up going down a rabbit hold and got derailed.

Can you confirm that this is a bug?

Thanks!

**Comment by surma** [comment]
So, I have a [test](https://github.com/surma/rollup-plugin-off-main-thread/blob/640c74295778b23b430b40b4c23c93b3ccbe7f4e/tests/fixtures/module-worker/entry.js#L14) for this, where it behaves correctly. Which version of rollup and my plugin are you using?

**Comment by slnovak** [comment]
Ah, okay. I've been using OMT in a project that uses `@rollup/plugin-node-resolve@7.1.1` which has a dependency on `rollup@^1.20.0`. Official Rollup plugins have [recently been updated for Rollup v2](https://github.com/rollup/plugins/pull/244), so once those plugins get published I'll be able to move to v2.2.0 and see if the issue reported here is resolved.

I'll keep you posted!

**Comment by andyricchuiti** [comment]
In agreement, this plugin is incredible! Thanks for the plugin.

I've run into the same problem as well. I'm not sure if it's my rollup config :/, but the initial rollup run (when i'm using `--watch`) has the transform function running first where `isEsmOutput` is still false, then isEsmOutput is calculated. after that, i'll save a file to refresh the build and each additional time the transform function has the correct isEsmOutput value. i'm on rollup 1.32.1 extending @open-wc's rollup config where the output format is `es` and 1.4.1 of this plugin.

**Comment by rogerscg** [comment]
I'm also experiencing this issue. Figured I'd bump since it's been a few months since the last comment.

**Comment by krzystof** [comment]
I do have the same issue. My problem is that I consume a package bundled using this plugin.

@surma if I check your test, here's what I see:

## Input: tests/fixtures/module-worker/entry.js

```js
const w = new Worker("./worker.js", { type: "module" });
w.addEventListener("message", ev => {
  window.parent.postMessage(ev.data, "*");
});
```

## Output: tests/fixtures/module-worker/build/entry.js
```js
const w = new Worker("./worker-d33410c2.js", {});
w.addEventListener("message", ev => {
  window.parent.postMessage(ev.data, "*");
});
```

If I now consume this output with another bundler (Webpack or Rollup), then the `{type: 'module'}` option is missing and I'm having problem.

**Comment by minht11** [comment]
I experience the same problem while using "esm" option.
Manually placing console.log inside local copy of "OMT" where ever variable "isEsmOutput" is used produces:
```
TEST:Start false
rollup v2.33.1
bundles src/index.html → dist...
TEST:transform {} false
TEST:outputOptions true
```
It seems "transform" hook runs before "outputOptions" and that causes "isEsmOutput" to be always false during transform phase.

**Comment by surma** [comment]
Finally getting around to look at this. Unfortunate that I didn’t notice that my test was moot, lol.

Sadly, there doesn’t seem to be a good way to get ahold of the output format ahead of time. So an additional option seems to be the only way around this. Happy to accept PRs if desired.

**Comment by surma** [comment]
This should be fixed now! Please re-open if it’s still broken.
