### ISSUE TITLE
Default setup not working if bundle is not in web root

### ISSUE THREAD

**Issue by panda-madness** [surma/rollup-plugin-off-main-thread#26]
If I modify the demo gist to serve the project root instead of the `dist` folder loading worker modules fails because it assumes all emitted files are directly under the document root.

[Here's](https://github.com/panda-madness/rollup-omt-bug-demo) a repo with reproduction.

<img width="625" alt="Screen Shot 2020-06-15 at 16 18 48" src="https://user-images.githubusercontent.com/6180087/84646438-ecd01f00-af23-11ea-80f0-8cf08ca5542f.png">

Note the actual comlink file is under `http://127.0.0.1:8080/dist/` in the screenshot above.

Edit: I've also tried to load the bundle with SystemJS, the bundle path resolves correctly but is missing the `js` file extension for some reason. [Same repo, systemjs branch](https://github.com/panda-madness/rollup-omt-bug-demo/tree/systemjs).

<img width="987" alt="Screen Shot 2020-06-15 at 16 25 03" src="https://user-images.githubusercontent.com/6180087/84647078-c959a400-af24-11ea-9b68-a05d85ed6491.png">

**Comment by gkjohnson** [comment]
Webpack now supports the following syntax for address this, which is the right way to load a Worker with a relative path in a module in a browser, as well:

```js
const worker = new Worker( new URL( './worker.js', import.meta.url ) );
```

It would be nice if the plugin supported this notation, as well.

**Comment by cortopy** [comment]
that's also the recommended way of dealing with web workers in snowpack https://github.com/snowpackjs/snowpack/issues/1280

**Comment by surma** [comment]
This plugin now supports the `new URL()` pattern as well. Can you check if this is still an issue?

**Comment by surma** [comment]
Closing this. But please re-open if it’s still broken
