### ISSUE TITLE
Build fails if output is "esm" and "silenceESMWorkerWarning" is true

### ISSUE THREAD

**Issue by minht11** [surma/rollup-plugin-off-main-thread#30]
I got following error:
```
[!] (plugin off-main-thread) Error: `output.format` 
must either be "amd" or "esm", got "esm"
```
this is because if opts.silenceESMWorkerWarning is true code only checks if output is not "amd" before throwing error. https://github.com/surma/rollup-plugin-off-main-thread/blob/15d7b01acf36a0532cca8f1ad663ec6460c64a6e/index.js#L59-L69

**Comment by surma** [comment]
Fixed in ea328ac
