### ISSUE TITLE
How can we actually use the worker bundles in a main webpack project?

### ISSUE THREAD

**Issue by MartinDawson** [surma/rollup-plugin-off-main-thread#43]
Hi,

I asked the question here too but nobody seems to know: https://stackoverflow.com/questions/67006986/how-to-use-a-web-worker-from-an-npm-library-into-main-webpack-project/67007352?noredirect=1#comment118483107_67007352

This plugin works and bundles the workers into separate files but then how can we actually use that in a main project like create-react-app or gatsby?

Do we need another webpack plugin which can scan our new node_module files for the workers to load them correctly?

**Comment by surma** [comment]
This is a rollup plugin. For webpack, look at [worker-loader](https://github.com/webpack-contrib/worker-loader).
